# Day 09. Exercise 02
# Metrics

## 0. Imports

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import joblib
import gdown
import warnings
warnings.filterwarnings('ignore')

In [4]:
url='https://drive.google.com/uc?id=1AlGvsJDSzPT_70caausx8bFuupIEZkfh&export=download'

output='day-of-week-not-scaled.csv'
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1AlGvsJDSzPT_70caausx8bFuupIEZkfh&export=download
To: /home/mirshod/Desktop/DSB11_ML_Advanced.ID_886524-1/src/ex02/day-of-week-not-scaled.csv
100%|██████████| 286k/286k [00:00<00:00, 309kB/s]

'day-of-week-not-scaled.csv'

In [5]:
url2='https://drive.google.com/uc?id=1PELTt93UDt-yp5xOECdlj9uy7kBMBKd4&export=download'
output='dayofweek.csv'
gdown.download(url2, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1PELTt93UDt-yp5xOECdlj9uy7kBMBKd4&export=download
To: /home/mirshod/Desktop/DSB11_ML_Advanced.ID_886524-1/src/ex02/dayofweek.csv
100%|██████████| 10.7k/10.7k [00:00<00:00, 199kB/s]

'dayofweek.csv'

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [6]:
df=pd.read_csv('day-of-week-not-scaled.csv')
df.head()

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
df2=pd.read_csv('dayofweek.csv')
df2.head()

   Unnamed: 0  dayofweek
0           0          4
1           1          4
2           2          4
3           3          4
4           4          4

In [8]:
df['dayofweek']=df2['dayofweek']
df.head()

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4

In [9]:
y=df['dayofweek']<5
X=df.drop(columns=['dayofweek'])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

## 2. SVM

1. Use the best parameters from the previous exercise and train the model of SVM.
2. You need to calculate `accuracy`, `precision`, `recall`, `ROC AUC`.

 - `precision` and `recall` should be calculated for each class (use `average='weighted'`)
 - `ROC AUC` should be calculated for each class against any other class (all possible pairwise combinations) and then weighted average should be applied for the final metric
 - the code in the cell should display the result as below:

```
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878
```

In [11]:
def show_scores(model):
  acc_score=accuracy_score(y_test, model.predict(X_test))
  precision_val=precision_score(y_test, model.predict(X_test), average='weighted')
  recall_val=recall_score(y_test, model.predict(X_test), average='weighted')
  roc_auc=roc_auc_score(y_test, model.predict_proba(X_test)[:, 1], average='weighted')

  print("===\tSCORES\t===")
  print('accuracy is ', acc_score)
  print('precision is ', precision_val)
  print('recall is ', recall_val)
  print('roc_auc is ', roc_auc)

In [12]:
svm=SVC(kernel='rbf', C=10, class_weight='balanced', gamma='auto', probability=True,
    random_state=21)
svm.fit(X_train, y_train)

SVC(C=10, class_weight='balanced', gamma='auto', probability=True,
    random_state=21)

In [13]:
show_scores(svm)

===	SCORES	===
accuracy is  0.9408284023668639
precision is  0.9426051088102819
recall is  0.9408284023668639
roc_auc is  0.976078167115903

## 3. Decision tree

1. The same task for decision tree

In [14]:
decision_tree=DecisionTreeClassifier(criterion='gini', max_depth=22, random_state=21)
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=22, random_state=21)

In [15]:
show_scores(decision_tree)

===	SCORES	===
accuracy is  0.9497041420118343
precision is  0.9498016315082519
recall is  0.9497041420118343
roc_auc is  0.9476452530697814

## 4. Random forest

1. The same task for random forest.

In [16]:
random_forest=RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=36, n_estimators=10)
random_forest.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=36, n_estimators=10)

In [17]:
show_scores(random_forest)

===	SCORES	===
accuracy is  0.9644970414201184
precision is  0.9660313122864619
recall is  0.9644970414201184
roc_auc is  0.9960130278526504

## 5. Predictions

1. Choose the best model.
2. Analyze: for which `weekday` your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which `labname` and for which `users`.
3. Save the model.

In [18]:
df_test = pd.concat([X_test, y_test], axis=1)

predictions = svm.predict(X_test)
df_test.rename(columns={'dayofweek': 'actual_is_weekday'}, inplace=True)

df_test['predicted_is_weekday'] = predictions


df_test['original_dayofweek'] = df.loc[X_test.index, 'dayofweek']
df_test['error'] = df_test['actual_is_weekday'] != df_test['predicted_is_weekday']

df_test.head()

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,actual_is_weekday,predicted_is_weekday,original_dayofweek,error
1010,43,21,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,True,True,0,False
476,2,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,False,False,5,False
705,38,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,True,True,1,False
1117,80,18,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,True,True,1,False
860,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,False,False,6,False

In [19]:
error_weekday=df_test.groupby('original_dayofweek')['error'].sum()/df_test.groupby('original_dayofweek')['error'].count()
error_weekday

original_dayofweek
0    0.033333
1    0.038462
2    0.068966
3    0.075949
4    0.136364
5    0.055556
6    0.041667
Name: error, dtype: float64

In [20]:
user_cols = [col for col in df_test.columns if col.startswith('uid_user_')]
user_error_rates = {}

for user_col in user_cols:
    user_data = df_test[df_test[user_col] == 1.0]
    if not user_data.empty:
        error_rate = user_data['error'].sum() / len(user_data)
        user_error_rates[user_col] = error_rate
    else:
        user_error_rates[user_col] = 0.0

users = pd.Series(user_error_rates).sort_values(ascending=False)

In [21]:
users

uid_user_21    0.428571
uid_user_17    0.250000
uid_user_26    0.222222
uid_user_24    0.200000
uid_user_31    0.125000
uid_user_3     0.100000
uid_user_4     0.068182
uid_user_20    0.058824
uid_user_25    0.041667
uid_user_14    0.037037
uid_user_13    0.000000
uid_user_10    0.000000
uid_user_0     0.000000
uid_user_1     0.000000
uid_user_2     0.000000
uid_user_19    0.000000
uid_user_18    0.000000
uid_user_16    0.000000
uid_user_15    0.000000
uid_user_11    0.000000
uid_user_12    0.000000
uid_user_23    0.000000
uid_user_28    0.000000
uid_user_27    0.000000
uid_user_22    0.000000
uid_user_29    0.000000
uid_user_30    0.000000
uid_user_6     0.000000
uid_user_7     0.000000
uid_user_8     0.000000
dtype: float64

In [22]:
users['uid_user_21']

np.float64(0.42857142857142855)

In [23]:
lab_cols = [col for col in df_test.columns if col.startswith('labname_')]
lab_error_rates = {}

for lab_col in lab_cols:
    lab_data = df_test[df_test[lab_col] == 1.0]
    if not lab_data.empty:
        error_rate = lab_data['error'].sum() / len(lab_data)
        lab_error_rates[lab_col] = error_rate
    else:
        lab_error_rates[lab_col] = 0.0

labs = pd.Series(lab_error_rates).sort_values(ascending=False)

In [24]:
labs

labname_laba04      0.160000
labname_code_rvw    0.150000
labname_lab05s      0.142857
labname_laba04s     0.111111
labname_laba05      0.090909
labname_project1    0.026316
labname_lab02       0.000000
labname_lab03       0.000000
labname_lab03s      0.000000
labname_laba06      0.000000
labname_laba06s     0.000000
dtype: float64

In [25]:
file='random_forest.joblib'
joblib.dump(random_forest, file)

['random_forest.joblib']

## 6. Function

1. Write a function that takes a list of different models and a corresponding list of parameters (dicts) and returns a dict that contains all the 4 metrics for each model.

In [26]:
def model_evaluation(models, params):
  for model, param in zip(models, params):
    model.set_params(**param)
    model.fit(X_train, y_train)
    show_scores(model)

In [27]:
models=[DecisionTreeClassifier(), RandomForestClassifier()]
params=[{'criterion':'gini', 'max_depth':22, 'random_state':21}, {'class_weight':'balanced', 'criterion':'entropy', 'max_depth':36, 'n_estimators':10}]
model_evaluation(models=models, params=params)

===	SCORES	===
accuracy is  0.9497041420118343
precision is  0.9498016315082519
recall is  0.9497041420118343
roc_auc is  0.9476452530697814
===	SCORES	===
accuracy is  0.9704142011834319
precision is  0.9718878631555068
recall is  0.9704142011834319
roc_auc is  0.995788409703504