In [1]:
import pandas as pd
import sqlite3

## 1

In [2]:
conn=sqlite3.connect('../data/checking-logs.sqlite')

## 2

In [3]:
pd.read_sql_query("PRAGMA table_info(checker)", conn)

   cid       name       type  notnull dflt_value  pk
0    0      index    INTEGER        0       None   0
1    1     status       TEXT        0       None   0
2    2    success    INTEGER        0       None   0
3    3  timestamp  TIMESTAMP        0       None   0
4    4  numTrials    INTEGER        0       None   0
5    5    labname       TEXT        0       None   0
6    6        uid       TEXT        0       None   0

In [4]:
checker=pd.read_sql_query('SELECT * FROM checker', conn)

## 3

In [5]:
checker.head(10)

,index,status,success,timestamp,numTrials,labname,uid
0,0,checking,0,2020-04-16 21:12:50.740474,5,None,admin_1
1,1,ready,0,2020-04-16 21:12:54.708365,5,code_rvw,admin_1
2,2,checking,0,2020-04-16 21:46:47.769088,7,None,admin_1
3,3,ready,0,2020-04-16 21:46:48.121217,7,lab02,admin_1
4,4,checking,0,2020-04-16 21:53:01.862637,6,code_rvw,admin_1
5,5,ready,0,2020-04-16 21:53:05.373389,6,code_rvw,admin_1
6,6,checking,0,2020-04-17 05:18:51.965864,1,None,None
7,7,ready,0,2020-04-17 05:19:02.744528,1,project1,user_4
8,8,checking,0,2020-04-17 05:22:35.249331,2,project1,user_4
9,9,ready,1,2020-04-17 05:22:45.549397,2,project1,user_4

## 4

In [6]:
query="""
SELECT COUNT(*) AS cnt 
FROM pageviews 
WHERE uid IN (
    SELECT uid 
    FROM checker 
    WHERE status = 'ready' 
    AND numTrials=1 AND labname IN ('laba04', 'laba04s', 'laba05', 'laba06', 'laba06s', 'project1')
);
"""

checker['cnt']=pd.read_sql_query(query, conn)

checker

,index,status,success,timestamp,numTrials,labname,uid,cnt
0,0,checking,0,2020-04-16 21:12:50.740474,5,None,admin_1,985.0
1,1,ready,0,2020-04-16 21:12:54.708365,5,code_rvw,admin_1,NaN
2,2,checking,0,2020-04-16 21:46:47.769088,7,None,admin_1,NaN
3,3,ready,0,2020-04-16 21:46:48.121217,7,lab02,admin_1,NaN
4,4,checking,0,2020-04-16 21:53:01.862637,6,code_rvw,admin_1,NaN
...,...,...,...,...,...,...,...,...
3397,3397,ready,0,2020-05-21 20:19:06.872761,7,laba06s,user_1,NaN
3398,3398,checking,0,2020-05-21 20:22:41.785725,8,laba06s,user_1,NaN
3399,3399,ready,0,2020-05-21 20:22:41.877806,8,laba06s,user_1,NaN
3400,3400,checking,0,2020-05-21 20:37:00.129678,9,laba06s,user_1,NaN
3401,3401,ready,0,2020-05-21 20:37:00.290491,9,laba06s,user_1,NaN

## 5

In [7]:
conn.close()