## 2

In [32]:
import pandas as pd
from sqlite3  import connect

## 3

In [ ]:
conn=connect('../data/checking-logs.sqlite')
pageviews=pd.read_sql_query("PRAGMA table_info(pageviews);", con=conn)

## 4

In [34]:
pageviews.head(10)

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

## 5

In [35]:
pageviews=pd.read_sql_query(
    """
    SELECT uid, datetime FROM pageviews WHERE uid LIKE 'user_%' ORDER BY uid ASC;
    """, con=conn, index_col='datetime', parse_dates=['datetime'])
pageviews

                                uid
datetime
2020-04-26 21:53:59.624136   user_1
2020-04-26 22:06:19.478143   user_1
2020-04-26 22:12:09.614497   user_1
2020-04-30 19:29:01.831635   user_1
2020-05-05 20:26:32.894852   user_1
...                             ...
2020-04-29 16:51:21.877630  user_30
2020-05-09 20:30:47.034282  user_30
2020-05-22 11:30:18.368990   user_5
2020-05-21 16:28:28.217529   user_9
2020-05-21 16:36:40.915488   user_9

[987 rows x 1 columns]

## 6

In [36]:
conn.close()